# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1bb9d88ea2e0c8ea28a65f334bf64ad0dcc5074be32de42b9078a7b15ea958353c190f2456a9bf03565e289432509a861f48780c0911f21a99d718670cdd8af1

test:
  secret_key_base: 693321f71cd60855401945e11665c34d74444d666bc22d9d31879284ffd43a87f7c855d2d62175b643a0b5d96fe46fd0d09d06620dae8d5c2e179a1f0ba004d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
